export interface iLocation {
    Address: string,
    Date_Updated: string,
    Image: string,
    IsActive: string,
    Latitude: string,
    LocationID: string,
    LocationTypeID: string,
    LocationType_Ref: string,
    Longitude: string,
    Name: string,
    Name_en: string,
    Phone: string,
    Title: string,
    Url_Image: string,
    User_Phone: string,
    //Star: string,
}